version: '3'

services:
  api:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - ".:/home/node/app"
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres